version: "1.0"

services:
  tta:
    build: .
    network_mode: host
    restart: unless-stopped
    container_name: tta
    volumes:
      #aria2下载目录，默认
      - /root/tta_downloads:/root/tta_downloads
      #挂载自定义的目录 方便发送 telgram 后删除文件，不设置，容器会找不到目录
      - /root/tta_temp:/root/tta_temp
    environment:
      TZ: Asia/Shanghai
      API_ID: 11111
      API_HASH: 11111
      BOT_TOKEN: 11111:11111
      JSON_RPC_URL: http://11111:6800/jsonrpc
      JSON_RPC_TOKEN: 11111
      JSON_RPC_PORTS: 6800
      JSON_RPC_URLS: "http://1.1.11.1"
      JSON_RPC_TOKENS: "11111"
      SEND_ID: 11111
      #      PROXY_IP:   #可选  代理ip
      #      PROXY_PORT:  #可选 代理端口
